### ISSUE TITLE
Fail to install

### ISSUE THREAD

**Issue by jared-94** [oweitman/LMS-shoutcast#1]
Hi,

I get this error when trying to activate the plugin:

`[16-09-27 09:06:28.4783] Slim::bootstrap::tryModuleLoad (290) Warning: Module [Plugins::NewShoutcast::Plugin] failed to load:
syntax error at /volume1/@appstore/SqueezeCenter/Cache/InstalledPlugins/Plugins/NewShoutcast/Plugin.pm line 266, near "$genres{ "
syntax error at /volume1/@appstore/SqueezeCenter/Cache/InstalledPlugins/Plugins/NewShoutcast/Plugin.pm line 266, near "} }"
Global symbol "$items" requires explicit package name at /volume1/@appstore/SqueezeCenter/Cache/InstalledPlugins/Plugins/NewShoutcast/Plugin.pm line 268.
Global symbol "$subgenre" requires explicit package name at /volume1/@appstore/SqueezeCenter/Cache/InstalledPlugins/Plugins/NewShoutcast/Plugin.pm line 269.
Global symbol "$subgenre" requires explicit package name at /volume1/@appstore/SqueezeCenter/Cache/InstalledPlugins/Plugins/NewShoutcast/Plugin.pm line 272.
Global symbol "$cb" requires explicit package name at /volume1/@appstore/SqueezeCenter/Cache/InstalledPlugins/Plugins/NewShoutcast/Plugin.pm line 276.
Global symbol "$items" requires explicit package name at /volume1/@appstore/SqueezeCenter/Cache/InstalledPlugins/Plugins/NewShoutcast/Plugin.pm line 276.
syntax error at /volume1/@appstore/SqueezeCenter/Cache/InstalledPlugins/Plugins/NewShoutcast/Plugin.pm line 280, near "}"
Can't use global @_ in "my" at /volume1/@appstore/SqueezeCenter/Cache/InstalledPlugins/Plugins/NewShoutcast/Plugin.pm line 284, near "= @_"
syntax error at /volume1/@appstore/SqueezeCenter/Cache/InstalledPlugins/Plugins/NewShoutcast/Plugin.pm line 298, near "}"
/volume1/@appstore/SqueezeCenter/Cache/InstalledPlugins/Plugins/NewShoutcast/Plugin.pm has too many errors.
Compilation failed in require at (eval 1132) line 1.
BEGIN failed--compilation aborted at (eval 1132) line 1.`

Is this a known problem?
My LMS is installed on a recent Synology NAS

**Comment by oweitman** [comment]
hi, thank you for installing.
you are the first known user who tried to install this plugin. 
i test the plugin  with
LMS  v7.9.0, 1465358341 / Perl-Version: 5.20.2 - x86_64-linux-gnu-thread-multi
on debian Jessie and
LMS v7.9.0 - 1461959934 / Perl Version: 5.22.1 - arm-linux-gnueabihf-thread-multi-64int 
on raspberry/piCorePlayer

for the first error in the list i changed a little bit the syntax, please reinstall/update the plugin.
the following errors with "Global symbol "???" requires explicit package name at" should not happen, maybe they caused by the first error.

if this doesnt help, please tel me your LMS and Perl-Version.
You can find this information in the LMS-settings on the "Information-Tab" (first section)

**Comment by jared-94** [comment]
Thanks for your help.
I've tried 0.15 version but still the same message.
My LMS version is 7.9.0 and Perl  5.18.4 - x86_64-linux

**Comment by oweitman** [comment]
ok, i changed some more of the hash-stuff in the code in v0.17
i test it on a fresh installed synology and it works 
Logitech Media Server Version: 7.9.0 - 1433513811 / Perl-Version: 5.18.4 - i686-linux

**Comment by jared-94** [comment]
Great!!!
It works perfectly now thank you very much!
